version: '3.1'

services:

  db:
    build: .
    restart: always
    volumes:
      - ".:/app"
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  pgadmin:
    image: dpage/pgadmin4:6.14
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: "true"

