version: '3.1'

services:

  db:
    build: .
    restart: always
    volumes:
      - ".:/app"
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
